In [1873]:
import tensorflow as tf
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow_hub as hub
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from imblearn.over_sampling import RandomOverSampler

In [1874]:
df_train = pd.read_csv("TENSORFLOW_DATA.csv")
df_test = pd.read_csv("TENSORFLOW_TES.csv")

In [1875]:
df = pd.concat([df_train,df_test])
df

(p) R  R (2)  R (5)  (p) G  G (2)  G (5)  (p) B  B (2)  B (5)  \
0      41     49     40     30     36     28     25     28     20   
1     189    188    182     81     88     80     76     82     74   
2     139    133    135    163    156    159     79     88     82   
3     123    138    124     78     89     78     46     53     44   
4     237    223    231    138    134    134    182    172    176   
..    ...    ...    ...    ...    ...    ...    ...    ...    ...   
5      84     86     76     51     53     45     25     27     22   
6      33    118     35     24     66     24     16     34     16   
7     115     96    117     69     59     71     33     31     35   
8      18     33     20     12     21     13     14     20     15   
9      79     86     79    101    105     99    131    133    129   

    (p) GreyScale  GreyScale (2)  GreyScale (5)  garut  solo  
0              37             39             31      0     1  
1              78            117            110      1     0  
2             162            141            143      1     0  
3              46            100             88      0     1  
4             237            165            168      1     0  
..            ...            ...            ...    ...   ...  
5              48             60             52      0     1  
6              25             78             26      0     1  
7              23             67             81      0     1  
8              13             24             15      0     1  
9             130            103             96      1     0  

[110 rows x 14 columns]

In [1876]:
X = df[df.columns[:-2]].values
y1 = df[df.columns[-1]].values
y2 = df[df.columns[-2]].values
Y = pd.DataFrame({"garut":y2,
                    "solo":y1}).values

In [1877]:
Y

array([[0, 1],
       [1, 0],
       [1, 0],
       [0, 1],
       [1, 0],
       [0, 1],
       [0, 1],
       [1, 0],
       [0, 1],
       [1, 0],
       [1, 0],
       [1, 0],
       [0, 1],
       [0, 1],
       [1, 0],
       [1, 0],
       [1, 0],
       [0, 1],
       [0, 1],
       [0, 1],
       [1, 0],
       [0, 1],
       [1, 0],
       [1, 0],
       [1, 0],
       [0, 1],
       [0, 1],
       [0, 1],
       [1, 0],
       [0, 1],
       [1, 0],
       [1, 0],
       [1, 0],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [0, 1],
       [0, 1],
       [1, 0],
       [1, 0],
       [0, 1],
       [1, 0],
       [0, 1],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [0, 1],
       [1, 0],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [1, 0],
       [0, 1],
       [1,

In [1878]:
scaler = StandardScaler()
X = scaler.fit_transform(X)
# data = np.hstack((X, np.reshape(Y, (-1, 1))))
data = np.hstack((X, Y))
transformed_df = pd.DataFrame(data, columns=df.columns)

In [1879]:
transformed_df

(p) R     R (2)     R (5)     (p) G     G (2)     G (5)     (p) B  \
0   -1.081936 -1.173729 -1.019893 -0.849367 -1.006746 -0.928246 -0.754293   
1    0.665477  0.860770  0.812911 -0.126419 -0.217466 -0.209669 -0.091243   
2    0.075134  0.055752  0.206278  1.035967  0.814669  0.882016 -0.052240   
3   -0.113775  0.128936  0.064301 -0.168946 -0.202287 -0.237306 -0.481272   
4    1.232205  1.373054  1.445357  0.681581  0.480743  0.536546  1.286860   
..        ...       ...       ...       ...       ...       ...       ...   
105 -0.574242 -0.632172 -0.555239 -0.551683 -0.748712 -0.693327 -0.754293   
106 -1.176391 -0.163798 -1.084429 -0.934420 -0.551392 -0.983521 -0.871302   
107 -0.208230 -0.485805 -0.026049 -0.296525 -0.657641 -0.334038 -0.650285   
108 -1.353494 -1.407916 -1.278035 -1.104525 -1.234423 -1.135528 -0.897304   
109 -0.633276 -0.632172 -0.516517  0.157090  0.040568  0.052888  0.623810   

        B (2)     B (5)  (p) GreyScale  GreyScale (2)  GreyScale (5)  garut  \
0   -0.906461 -0.866405      -0.755211      -1.096895      -0.987503    0.0   
1   -0.092742 -0.120002      -0.282877       0.130300       0.129722    1.0   
2   -0.002329 -0.009424       0.684832       0.507899       0.596410    1.0   
3   -0.529739 -0.534671      -0.651528      -0.137165      -0.181404    0.0   
4    1.263456  1.289869       1.548858       0.885497       0.949963    1.0   
..        ...       ...            ...            ...            ...    ...   
105 -0.921530 -0.838761      -0.628487      -0.766496      -0.690520    0.0   
106 -0.816048 -0.921694      -0.893455      -0.483297      -1.058214    0.0   
107 -0.861254 -0.659071      -0.916496      -0.656363      -0.280399    0.0   
108 -1.027012 -0.935516      -1.031699      -1.332894      -1.213777    0.0   
109  0.675770  0.640222       0.316181      -0.089966      -0.068268    1.0   

     solo  
0     1.0  
1     0.0  
2     0.0  
3     1.0  
4     0.0  
..    ...  
105   1.0  
106   1.0  
107   1.0  
108   1.0  
109   0.0  

[110 rows x 14 columns]

In [1880]:
len(transformed_df[transformed_df["garut"]==1]), len(transformed_df[transformed_df["solo"]==0])

(55, 55)

In [1881]:
X[:100].shape
Y[:100].shape

(100, 2)

In [1882]:
X_train, X_valid, Y_train, Y_valid = train_test_split(X[:100], Y[:100], test_size=0.8, random_state=0)

In [1883]:
model = tf.keras.Sequential([
                             tf.keras.layers.Dense(12, activation='relu'), # if x <= 0 --> 0, x > 0 --> x
                             tf.keras.layers.Dense(24, activation='relu'), #bisa ganti
                             tf.keras.layers.Dense(2, activation="sigmoid") #bisa ditambah
])

In [1884]:
model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.01), #ganti
              loss=tf.keras.losses.BinaryCrossentropy(), #ganti
              metrics=['accuracy'])

In [1885]:
model.evaluate(X_train, Y_train)

1/1 [==============================] - 1s 937ms/step - loss: 0.6347 - accuracy: 0.4500


[0.6346992254257202, 0.44999998807907104]

In [1886]:
model.evaluate(X_valid, Y_valid)

3/3 [==============================] - 0s 6ms/step - loss: 0.6456 - accuracy: 0.5000


[0.6455541253089905, 0.5]

In [1887]:
model.fit(X_train, Y_train, batch_size=16, epochs=20, validation_data=(X_valid, Y_valid))

Epoch 1/20
2/2 [==============================] - 2s 182ms/step - loss: 0.6228 - accuracy: 0.5000 - val_loss: 0.5493 - val_accuracy: 0.8250
Epoch 2/20
2/2 [==============================] - 0s 109ms/step - loss: 0.4998 - accuracy: 0.8500 - val_loss: 0.4635 - val_accuracy: 0.8375
Epoch 3/20
2/2 [==============================] - 0s 115ms/step - loss: 0.4046 - accuracy: 0.8500 - val_loss: 0.3886 - val_accuracy: 0.8375
Epoch 4/20
2/2 [==============================] - 0s 94ms/step - loss: 0.3151 - accuracy: 0.8500 - val_loss: 0.3316 - val_accuracy: 0.8375
Epoch 5/20
2/2 [==============================] - 0s 73ms/step - loss: 0.2464 - accuracy: 0.8500 - val_loss: 0.3011 - val_accuracy: 0.8500
Epoch 6/20
2/2 [==============================] - 0s 69ms/step - loss: 0.1957 - accuracy: 0.8500 - val_loss: 0.2942 - val_accuracy: 0.8500
Epoch 7/20
2/2 [==============================] - 0s 86ms/step - loss: 0.1575 - accuracy: 0.9500 - val_loss: 0.3084 - val_accuracy: 0.8500
Epoch 8/20
2/2 [========

In [1888]:
X_test = X[100:]


In [1889]:
#model.save

In [1890]:
result = model.predict(X_test)

1/1 [==============================] - 0s 151ms/step


In [1891]:
persenan =result
persenan

array([[9.9998343e-01, 2.9003952e-05],
       [9.9999881e-01, 2.3488592e-06],
       [3.9513120e-03, 9.9862880e-01],
       [9.8036319e-01, 2.1744110e-02],
       [9.6723425e-01, 3.8067225e-02],
       [2.0654541e-05, 9.9999505e-01],
       [1.8190103e-05, 9.9999779e-01],
       [4.4489279e-05, 9.9998367e-01],
       [3.8278239e-07, 9.9999994e-01],
       [9.2773068e-01, 8.6170733e-02]], dtype=float32)

In [1892]:
a = np.hsplit(result,2)

In [1893]:
kiri = a[0]

In [1894]:
kanan = a[1]

In [1895]:
for i in range(10):
    for j in range(1):
        if kiri[i][j] < kanan[i][j]:
            print("[0,1] = Solo")
        else:
            print("[1,0] = Garut")

[1,0] = Garut
[1,0] = Garut
[0,1] = Solo
[1,0] = Garut
[1,0] = Garut
[0,1] = Solo
[0,1] = Solo
[0,1] = Solo
[0,1] = Solo
[1,0] = Garut


In [1896]:
result = np.around(result)

In [1897]:
result

array([[1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.]], dtype=float32)

In [1898]:
print("        Garut     Solo")
persenan

        Garut     Solo


array([[9.9998343e-01, 2.9003952e-05],
       [9.9999881e-01, 2.3488592e-06],
       [3.9513120e-03, 9.9862880e-01],
       [9.8036319e-01, 2.1744110e-02],
       [9.6723425e-01, 3.8067225e-02],
       [2.0654541e-05, 9.9999505e-01],
       [1.8190103e-05, 9.9999779e-01],
       [4.4489279e-05, 9.9998367e-01],
       [3.8278239e-07, 9.9999994e-01],
       [9.2773068e-01, 8.6170733e-02]], dtype=float32)

In [1899]:
print("        Garut     Solo")
persenan

        Garut     Solo


array([[9.9998343e-01, 2.9003952e-05],
       [9.9999881e-01, 2.3488592e-06],
       [3.9513120e-03, 9.9862880e-01],
       [9.8036319e-01, 2.1744110e-02],
       [9.6723425e-01, 3.8067225e-02],
       [2.0654541e-05, 9.9999505e-01],
       [1.8190103e-05, 9.9999779e-01],
       [4.4489279e-05, 9.9998367e-01],
       [3.8278239e-07, 9.9999994e-01],
       [9.2773068e-01, 8.6170733e-02]], dtype=float32)